- type: job
  id: CEGuard
  setPreference: true
  name: ce-job-name-guard
  description: ce-job-desc-guard
  playTimeTracker: CEJobGuard
  #startingGear: CEGuardGear
  icon: CEJobIconGuard
  supervisors: ce-job-supervisors-guard-commander
  canBeAntag: false
  special:
    - !type:CEAddTradingReputationSpecial
      factions:
      - EmpireGuard

#- type: startingGear
#  id: CEGuardGear
#  equipment:
#    keys: CEKeyRingGuard
#    belt: CEWalletFilledTest
